### ISSUE TITLE
Are MIST_codes only compatible with MESA v7503?

### ISSUE THREAD

**Issue by tianzhijia** [jieunchoi/MIST_codes#1]
I installed MESA v 8118 (the latest version until now). When I tried to run MIST, there appeared to be an error.
Are MIST_codes only compatible with MESA v7503 for now?

**Comment by jieunchoi** [comment]
Can you explain what you meant by you tried to run MIST?

There's been some shuffling around & renaming of things in the newer versions of MESA, so it probably isn't compatible with versions post-7503.

**Comment by tianzhijia** [comment]
It's a directory or path problem on my macbook. 
I set up the `$MESAWORK_DIR`,`$ISO_DIR` and `$MIST_CODE_DIR` in /etc/profile. But it didn't work and showed `ImportError: No module named read_mist_models`,  when I `import read_mist_models` on python.
Then I used the sentence `sys.path.append('/Users/tianzhijia/work/isos/MIST/MIST_codes/plot_routine')` to add the path. It worked well. 
It seems that environment variables has not been setup well in /etc/profile. I'm a new user of python, I want to know if there are some better methods to set the path.
Thx.

**Comment by jieunchoi** [comment]
Are you just trying to use read_mist_models.py? You should be just downloading that Python code and don't need to set up the environment variables like MESAWORK_DIR, etc.

**Comment by tianzhijia** [comment]
I will add the path of mist code to the $PATH. I think it works.
Thx
